### ISSUE TITLE
Write permission given to me by mistake

### ISSUE THREAD

**Issue by phanect** [larzconwell/tlsopts#1]
Hi, @larzconwell,

You may have given me write permission to me by mistake.
I tried to create test branch and made one test commit, and succeeded.

I recommend you to check permission of tlsops repo.

**Comment by larzconwell** [comment]
Hi!

I should have reached out to you before sorry about that, I actually gave them to you on purpose, I noticed you contributed a lot to geddy, and this module was originally created for it. I have since stopped using Node so I figured if anything came up in the future while working on Geddy it'd be easier if you already had access.

If you don't want access that's alright as well just let me know and I'll take you off. Sorry about the confusion!

**Comment by phanect** [comment]
Got it, Thanks :)

**Comment by larzconwell** [comment]
No problem! You're also a collab on the npm site as well so you're aware.
